---
- name: Configure system access and Docker
  hosts: webserver
  become: true
  vars_files:
    - vars/private.yml
    - vars/vault.yml
  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: "docker"
        state: started
        enabled: true

    - name: Create Default Dockge directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/dockge
        - /opt/stacks
    - name: Copy Docker docker-compose file
      ansible.builtin.copy:
        src: templates/dockge/dockge-compose.yml
        dest: /opt/dockge/docker-compose.yml
        mode: '0600'
- name: Set up Tailscale
  hosts: webserver
  become: true
  vars_files:
    - vars/private.yml
    - vars/vault.yml
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ tailscale_key }}"
        tailscale_args: "--ssh"
