---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/private.yml
  tasks:
    - name: Add ansible-access group.
      ansible.builtin.group:
        name: ansible-access
        state: present
    - name: Allow 'ansible-access' group to sudo without password.
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%ansible-access'
        line: '%ansible-access ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Create user and add to ansible-access group.
      ansible.builtin.user:
        name: "{{ login_user }}"
        group: ansible-access
        append: yes

- name: Set up Tailscale with SSH access.
  hosts: all
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"