---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: Ensure DNSStubListener is set to no
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: 'DNSStubListener=no'
    state: present
  notify: restart systemd-resolved

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: '0644'
  notify: restart dnsmasq

- name: Ensure dnsmasq is running and enabled
  service:
    name: dnsmasq
    state: started
    enabled: yes