---
- name: Deploy Applications
  hosts: webserver
  become: true
  vars_files:
    - vars/private.yml
    - vars/vault.yml
  tasks:
    - name: Ensure ci6ndex stacks directory exists 
      ansible.builtin.file:
        path: "/opt/dockge/stacks/ci6ndex"
        state: directory
        mode: '0755'
        recurse: true
    - name: Copy ci6ndex compose file
      ansible.builtin.copy:
        src: templates/deployments/ci6ndex/compose.yml
        dest: /opt/dockge/stacks/ci6ndex/compose.yml
        mode: '0600'
        directory_mode: '0755'
    - name: Ensure paperless stacks directory exists
      ansible.builtin.file:
        path: "/opt/dockge/stacks/paperless-ngx"
        state: directory
        mode: '0755'
        recurse: true
    - name: Copy paperless compose file
      ansible.builtin.copy:
        src: templates/deployments/paperless-ngx/compose.yml
        dest: /opt/dockge/stacks/paperless-ngx/compose.yml
        mode: '0600'
        directory_mode: '0755'
    - name: Copy paperless settings file
      ansible.builtin.copy:
        src: templates/deployments/paperless-ngx/docker-compose.env
        dest: /opt/dockge/stacks/paperless-ngx/docker-compose.env
        mode: '0600'
        directory_mode: '0755'
    - name: Copy paperless env file
      ansible.builtin.copy:
        src: templates/deployments/paperless-ngx/.env
        dest: /opt/dockge/stacks/paperless-ngx/.env
        mode: '0600'
        directory_mode: '0755'
