---
- name: Ansible playbook for all hosts
  hosts: all
  become: yes
  vars_files:
    - vars/ubuntu_vault.yml
  vars:
    ansible_become_password: "{{ vault_ansible_become_pass }}"
  roles:
    - ubuntu
  remote_user: ansible
  tags: ubuntu

- name: Ansible playbook for configuring DNS
  hosts: dns
  become: yes
  vars_files:
      - vars/dns_vault.yml
  vars:
    ansible_become_password: "{{ vault_ansible_become_pass }}"
  roles:
    - brihome_dns
  remote_user: ansible
  tags: dns