---
- name: Ansible playbook for all hosts
  hosts: all
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - ubuntu
  remote_user: ansible
  tags: ubuntu

- name: Ansible playbook for configuring DNS
  hosts: dns
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - brihome_dns
  remote_user: ansible
  tags: dns

- name: Ansible playbook for configuring Docker
  hosts: docker
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
      - brihome_docker
  remote_user: ansible
  tags: docker