---
- name: Configure system access and Docker
  hosts: webserver
  become: true
  vars_files:
    - group_vars/private.yml
    - group_vars/vault.yml
  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: "docker"
        state: started
        enabled: true
