---
- name: Configure system access and Docker
  hosts: webserver
  become: true
  vars_files:
    - vars/private.yml
    - vars/vault.yml
  tasks:
    - name: Ensure Docker service is running
      systemd:
        name: "docker"
        state: started
        enabled: yes
      ignore_errors: true

- name: Set up Tailscale and Docker
  hosts: webserver
  become: true
  vars_files:
    - vars/private.yml
    - vars/vault.yml
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ tailscale_key }}"
        tailscale_args: "--ssh"