---
- name: Install docker
  include_role:
    name: geerlingguy.docker
- name: Add to sudoers
  lineinfile:
    dest: /etc/sudoers.d/caddy
    line: "%caddy ALL=(ALL) ALL"
    state: present
    create: yes
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440
- name: Ensure deployment directory exists
  file:
    path: /home/ansible/docker
    state: directory
    mode: '0755'
- name: Deploy Caddy
  template:
      src: docker-compose.yml.j2
      dest: /home/ansible/docker/docker-compose.yml
- name: Ensure /etc/caddy directory exists
  file:
    path: /etc/caddy
    state: directory
    mode: '0755'
- name: Deploy Caddy configuration
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'