---

- name: Add to sudoers
  lineinfile:
    dest: /etc/sudoers.d/caddy
    line: "%caddy ALL=(ALL) ALL"
    state: present
    create: yes
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440

- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Ensure Caddy service is enabled and started
  service:
    name: caddy
    state: started
    enabled: yes

- name: Deploy Caddy configuration
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'
  notify: restart caddy

- name: Deploy Caddy systemd service file
  template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: '0644'
  notify: restart caddy

- name: Reload systemd to apply new service
  command: systemctl daemon-reload

- name: Ensure Caddy service is enabled and started
  service:
    name: caddy
    state: started
    enabled: yes