---
- name: 'Update APT package cache'
  apt:
    update_cache: yes
    upgrade: safe

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
    autoclean: true
  notify: reboot

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Configure unattended-upgrades settings
  ansible.builtin.copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::Enable "1";
      // Only install security updates automatically
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}-security";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Mail "root";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"

- name: Install packages
  apt:
    package:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - python3-pip
    state: present

- name: Set up Tailscale
  include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ tailscale_key }}"
    tailscale_args: "--ssh"
