---
- name: Install docker
  include_role:
    name: geerlingguy.docker
- name: Ensure deployment directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home/ansible/docker
    - /home/ansible/docker/open-web-ui
    - /home/ansible/docker/hoarder
    - /home/ansible/docker/paperless
    - /home/ansible/docker/mealie
    - /home/ansible/docker/searxng
#    Open Webui
- name: Deploy Open Web UI
  template:
    src: open_webui/docker-compose.yml.j2
    dest: /home/ansible/docker/open-web-ui/docker-compose.yml
#    Hoarder
- name: Check if .env file exists
  stat:
    path: /home/ansible/docker/hoarder/.env
  register: hoarder_env_file
- name: Create .env file for Hoarder
  template:
    src: hoarder/env.j2
    dest: /home/ansible/docker/hoarder/.env
    mode: '0644'
  when: not hoarder_env_file.stat.exists
- name: Deploy Hoarder
  template:
    src: hoarder/docker-compose.yml.j2
    dest: /home/ansible/docker/hoarder/docker-compose.yml
#   Paperless
- name: Check if .env file exists
  stat:
    path: /home/ansible/docker/paperless/.env
  register: paperless_dotenv_file
- name: Check if docker.env file exists
  stat:
    path: /home/ansible/docker/paperless/docker-compose.env
  register: paperless_dockerenv_file
- name: Create docker.env file for Paperless
  template:
    src: paperless/docker-compose.env.j2
    dest: /home/ansible/docker/paperless/docker-compose.env
    mode: '0644'
  when: not paperless_dockerenv_file.stat.exists
- name: Create .env file for Paperless
  template:
    src: paperless/env.j2
    dest: /home/ansible/docker/paperless/.env
    mode: '0644'
  when: not paperless_dotenv_file.stat.exists
- name: Create consumption and export directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home/ansible/docker/paperless/consume
    - /home/ansible/docker/paperless/export
- name: Deploy Paperless
  template:
    src: paperless/docker-compose.yml.j2
    dest: /home/ansible/docker/paperless/docker-compose.yml
# Mealie
- name: Deploy Mealie
  template:
    src: mealie/docker-compose.yml.j2
    dest: /home/ansible/docker/mealie/docker-compose.yml
# Searxng
- name: Check if .env file exists
  stat:
    path: /home/ansible/docker/searxng/.env
  register: searxng_dotenv_file

- name: Check if searxng settings dir exists
  stat:
    path: /home/ansible/docker/searxng/settings
  register: searxng_settings_dir

- name: Create .env file for Searxng
  template:
    src: searxng/env.j2
    dest: /home/ansible/docker/searxng/.env
    mode: '0644'
  when: not searxng_dotenv_file.stat.exists

- name: Create settings directory for Searxng
  file:
    path: /home/ansible/docker/searxng/settings/
    state: directory
    mode: '0755'
  when: not searxng_settings_dir.stat.exists  

- name: Copy Searxng settings.yml file
  template:
    src: searxng/settings/settings.yml.j2
    dest: /home/ansible/docker/searxng/settings/settings.yml
    mode: '0644'

- name: Copy Searxng limiter file
  template:
    src: searxng/settings/limiter.toml.j2
    dest: /home/ansible/docker/searxng/settings/limiter.toml
    mode: '0644'

- name: Deploy Searxng
  template:
    src: searxng/docker-compose.yml.j2
    dest: /home/ansible/docker/searxng/docker-compose.yml
    mode: '0644'