version: '3.8'
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/dockge/stacks:/opt/stacks
    environment:
      - DOCKGE_UNIX_SOCKET_PATH=/var/run/docker.sock
