ansible_connection: ssh
ansible_python_interpreter: /usr/bin/python3
ansible_become_password: "{{ vault_ansible_become_pass }}"
local_domain: "{{ vault_local_domain }}"
reverse_proxy_ip_address: "{{ vault_reverse_proxy_ip_address }}"
open_web_ui_ip: "{{ vault_open_web_ui_ip }}"
open_web_ui_port: "{{ vault_open_web_ui_port }}"
proxmox_ip: "{{ vault_proxmox_ip }}"
proxmox_port: "{{ vault_proxmox_port }}"
homeassistant_ip: "{{ vault_homeassistant_ip }}"
homeassistant_port: "{{ vault_homeassistant_port }}"
hoarder_ip: "{{ vault_hoarder_ip }}"
hoarder_port: "{{ vault_hoarder_port }}"
paperless_ip: "{{ vault_paperless_ip }}"
paperless_port: "{{ vault_paperless_port }}"
mealie_ip: "{{ vault_mealie_ip }}"
mealie_port: "{{ vault_mealie_port }}"
searxng_ip: "{{ vault_searxng_ip }}"
searxng_port: "{{ vault_searxng_port }}"
searxng_secret_key: "{{ vault_searxng_secret_key }}"